title: "Узнал и поделился"
description: >-
  Когда хочется рассказать о том, что я узнал или научился делать.
baseurl: ""
url: "https://zaraysky.github.io"
author: "Ваше Имя"

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed

collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
